# Generated by Django 4.2.3 on 2023-09-27 11:38

import admin_panel_app.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandNumberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_number', models.IntegerField(verbose_name='Номер отдела/Сокращение')),
                ('command_name', models.CharField(max_length=150, verbose_name='Наименование отдела')),
                ('show', models.BooleanField(default=True, verbose_name='Отображать отдел')),
            ],
            options={
                'verbose_name': 'номер отдела',
                'verbose_name_plural': 'номера отделов',
                'db_table': 'ToDo_tasks_commandnumbermodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=150, verbose_name='Отчество')),
                ('personnel_number', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Табельный номер')),
                ('user_phone', models.IntegerField(default=None, null=True, verbose_name='№ телефона')),
                ('right_to_sign', models.BooleanField(default=False, verbose_name='Право подписывать')),
                ('check_edit', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('can_make_task', models.BooleanField(default=True, verbose_name='Возможность выдавать задания')),
                ('cpe_flag', models.BooleanField(default=False, verbose_name='Флаг ГИП (техническая метка)')),
                ('mailing_list_check', models.BooleanField(default=True, verbose_name='Получать рассылку')),
                ('work_status', models.BooleanField(default=True, verbose_name='Сотрудник работает')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'db_table': 'ToDo_tasks_employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupDepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_dep_abr', models.CharField(max_length=10, verbose_name='Сокращенное название управления')),
                ('group_dep_name', models.CharField(max_length=250, verbose_name='Полное название управления')),
                ('show', models.BooleanField(default=True, verbose_name='Отображать отдел')),
            ],
            options={
                'verbose_name': 'управление',
                'verbose_name_plural': 'управления',
                'db_table': 'ToDo_tasks_groupdepartmentmodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobTitleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'должности',
                'db_table': 'ToDo_tasks_jobtitlemodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CityDepModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('name_dep', models.CharField(max_length=350, verbose_name='Наименование организации')),
            ],
            options={
                'verbose_name': 'город/организация',
                'verbose_name_plural': 'города/организации',
            },
        ),
        migrations.CreateModel(
            name='MoreDetailsEmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=admin_panel_app.models.upload_to, verbose_name='Файл')),
                ('outside_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Внешняя почта')),
                ('mobile_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Мобильный телефон')),
                ('date_birthday', models.DateField(blank=True, null=True, verbose_name='Дата приказа/поручения')),
                ('room', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер комнаты')),
                ('date_birthday_show', models.BooleanField(default=False, null=True, verbose_name='Отображать день рождения')),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_panel_app.employeemodel', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'дополнительная информация по сотруднику',
                'verbose_name_plural': 'дополнительная информация по сотрудникам',
            },
        ),
    ]
