# Generated by Django 4.2.3 on 2023-09-27 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moredetailsemployeemodel',
            name='city_dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_panel_app.citydepmodel', verbose_name='Город/Подразделение'),
        ),
        migrations.AlterField(
            model_name='moredetailsemployeemodel',
            name='date_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
    ]
