# Generated by Django 4.2.3 on 2023-09-29 18:37

import admin_panel_app.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_app', '0002_moredetailsemployeemodel_city_dep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moredetailsemployeemodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=admin_panel_app.models.upload_to, verbose_name='Файл'),
        ),
    ]
