# Generated by Django 4.2.3 on 2023-09-29 18:51

import admin_panel_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_app', '0003_alter_moredetailsemployeemodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moredetailsemployeemodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=admin_panel_app.models.upload_to, verbose_name='Файл'),
        ),
    ]
