# Generated by Django 4.2.5 on 2023-09-30 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_app', '0004_alter_moredetailsemployeemodel_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanEditEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_panel_app.employeemodel', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'может редактировать сотрудников',
                'verbose_name_plural': 'может редактировать сотрудников',
            },
        ),
    ]
