# Generated by Django 4.2.6 on 2024-02-27 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_app', '0006_caneditemployee_can_change_emp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsEmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('count_people_in_company', models.IntegerField(blank=True, default=None, null=True, verbose_name='Количество человек')),
                ('employee_action', models.IntegerField(choices=[(1, 'Работает'), (0, 'Уволился')], default=1, verbose_name='Статус задания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel_app.employeemodel', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'статистика сотрудника',
                'verbose_name_plural': 'статистика сотрудников',
            },
        ),
    ]
