# Generated by Django 4.2.6 on 2024-07-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_app', '0007_statsemployeemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='moredetailsemployeemodel',
            name='send_email_salary_blank',
            field=models.BooleanField(default=False, verbose_name='Отсылать расчетный листок'),
        ),
    ]
