# Generated by Django 4.2.6 on 2024-11-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_app', '0008_moredetailsemployeemodel_send_email_salary_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='moredetailsemployeemodel',
            name='archive_access',
            field=models.BooleanField(default=False, verbose_name='Доступ к архиву'),
        ),
    ]
