# Generated by Django 4.2.5 on 2023-09-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandNumberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_number', models.IntegerField(verbose_name='Номер отдела/Сокращение')),
                ('command_name', models.CharField(max_length=150, verbose_name='Наименование отдела')),
            ],
            options={
                'verbose_name': 'номер отдела',
                'verbose_name_plural': 'номера отделов',
                'db_table': 'ToDo_tasks_commandnumbermodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=150, verbose_name='Отчество')),
                ('personnel_number', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Табельный номер')),
                ('user_phone', models.IntegerField(default=None, null=True, verbose_name='№ телефона')),
                ('right_to_sign', models.BooleanField(default=False, verbose_name='Право подписывать')),
                ('check_edit', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('can_make_task', models.BooleanField(default=True, verbose_name='Возможность выдавать задания')),
                ('cpe_flag', models.BooleanField(default=False, verbose_name='Флаг ГИП (техническая метка)')),
                ('mailing_list_check', models.BooleanField(default=True, verbose_name='Получать рассылку')),
                ('work_status', models.BooleanField(default=True, verbose_name='Сотрудник работает')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'db_table': 'ToDo_tasks_employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupDepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_dep_abr', models.CharField(max_length=10, verbose_name='Сокращенное название управления')),
                ('group_dep_name', models.CharField(max_length=250, verbose_name='Полное название управления')),
            ],
            options={
                'verbose_name': 'управление',
                'verbose_name_plural': 'управления',
                'db_table': 'ToDo_tasks_groupdepartmentmodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobTitleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'должности',
                'db_table': 'ToDo_tasks_jobtitlemodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccessLevelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(max_length=50, verbose_name='Наименование доступа')),
            ],
            options={
                'verbose_name': 'уровень доступа',
                'verbose_name_plural': 'уровни доступа',
            },
        ),
    ]
