# Generated by Django 4.2.5 on 2023-09-29 19:04

from django.db import migrations, models
import django.db.models.deletion
import phonebook_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityDepModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('name_dep', models.CharField(max_length=350, verbose_name='Наименование организации')),
            ],
            options={
                'verbose_name': 'город/организация',
                'verbose_name_plural': 'города/организации',
            },
        ),
        migrations.CreateModel(
            name='MoreDetailsEmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=phonebook_app.models.upload_to, verbose_name='Файл')),
                ('outside_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Внешняя почта')),
                ('mobile_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Мобильный телефон')),
                ('date_birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('room', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер комнаты')),
                ('date_birthday_show', models.BooleanField(default=False, null=True, verbose_name='Отображать день рождения')),
                ('city_dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phonebook_app.citydepmodel', verbose_name='Город/Подразделение')),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='phonebook_app.employeemodel', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'дополнительная информация по сотруднику',
                'verbose_name_plural': 'дополнительная информация по сотрудникам',
            },
        ),
        migrations.DeleteModel(
            name='AccessLevelModel',
        ),
    ]
