# Generated by Django 4.2.5 on 2023-09-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook_app', '0002_citydepmodel_moredetailsemployeemodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citydepmodel',
            options={'managed': False, 'verbose_name': 'город/организация', 'verbose_name_plural': 'города/организации'},
        ),
        migrations.AlterModelOptions(
            name='moredetailsemployeemodel',
            options={'managed': False, 'verbose_name': 'дополнительная информация по сотруднику', 'verbose_name_plural': 'дополнительная информация по сотрудникам'},
        ),
    ]
